CampusSportswear\Bundle\OrderBundle\Entity\CampusSportswearOrder:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        itemDescription:
            type: text
            column: item_description
        itemQuantity:
            type: integer
            column: item_quantity
        itemQuotedPrice:
            type: float
            column: item_quoted_price
        itemRecommendedPrice:
            type: float
            column: item_recommended_price
        orderAddress:
            type: string
            length: 255
            column: order_address
        comment:
            type: text
        itemGraphic:
            type: string
            length: 255
            column: item_graphic
        orderStatus:
            type: smallint
            column: order_status
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks: {  }
